// Staff-reviewed downward correction of a synthetic-content declaration
// (AI Act Art. 50 + GDPR Art. 16 rectification). Decision **D12**.
//
// Pure core: no I/O, no clock, no Prisma. The route
// (lib/routes/provenance-correction.ts) is the shell.
//
// WHY THIS EXISTS
// ---------------
// Author-facing provenance is MONOTONIC: a declaration may be raised, never
// lowered, and the edit path returns 409 on an attempt. That fails safe — the
// worst case is over-disclosure — but it left a real gap: an author who
// mis-tapped "AI-generated" on a photograph they took themselves had **no way to
// correct it**, and GDPR Art. 16 gives a data subject the right to have
// inaccurate personal data rectified. A permanent, uncorrectable, wrong label is
// exactly what that article is about.
//
// WHY IT IS STAFF-ONLY (D12)
// --------------------------
// A user-initiated lowering path IS the laundering path — it hands the author the
// precise capability monotonicity exists to deny, and an attacker's "I made a
// mistake" is indistinguishable from a truthful one. Art. 16 grants the right to
// have inaccurate data corrected; it does not grant the right to correct it
// unilaterally. A reviewed correction with an audit trail discharges the duty and
// keeps the guarantee.
//
// WHAT STAYS IMPOSSIBLE
// ---------------------
// `PLATFORM_GENERATED` is not correctable by anyone, including staff. There the
// platform's own generation record is the evidence, so a "correction" would not be
// rectifying an inaccuracy — it would be falsifying our own attestation.

import { disclosureStrength } from "./resolve.js";
import type { SyntheticBasis, SyntheticSourceType } from "./types.js";

/** The stored provenance of the row being corrected. */
export interface CorrectionSubject {
  readonly sourceType: SyntheticSourceType;
  readonly basis: SyntheticBasis | null;
}

export type CorrectionRefusalCode =
  /** The stored basis is PLATFORM_GENERATED — our own record, never correctable. */
  | "PROVENANCE_PLATFORM_ATTESTED"
  /** The requested value equals the stored one; nothing to correct. */
  | "PROVENANCE_UNCHANGED";

export type CorrectionPlan =
  | {
      readonly kind: "apply";
      readonly from: SyntheticSourceType;
      readonly to: SyntheticSourceType;
      /**
       * The basis to store alongside the corrected value.
       *
       * NOT a new `STAFF_CORRECTED` enum member, deliberately. `basis` answers
       * "how do we believe this?", and after a rectification the answer is still
       * the author's (corrected) statement — a staff member does not have
       * independent knowledge of how the content was made, only of the fact that
       * the recorded answer was wrong. Adding a member would also change an
       * API-visible vocabulary (`ProvenanceView.basis`) and the D2 four-answer
       * framing, for information the audit event already carries better: WHO
       * corrected it, WHEN, and WHY.
       *
       * Null exactly when the corrected value is `UNKNOWN`, preserving the
       * invariant on {@link Provenance} that a basis without a source type is
       * meaningless.
       */
      readonly basis: SyntheticBasis | null;
      /**
       * True when this correction REDUCES disclosure — the case that only staff
       * may perform, and the one worth surfacing in monitoring. A raise is
       * permitted here too (staff fixing an under-declaration), and is not
       * privileged: the author could have done it themselves.
       */
      readonly reducesDisclosure: boolean;
    }
  | {
      readonly kind: "refuse";
      readonly code: CorrectionRefusalCode;
      readonly message: string;
    };

const REFUSALS: Record<CorrectionRefusalCode, string> = {
  PROVENANCE_PLATFORM_ATTESTED:
    "This content was generated by the platform's own AI feature. That record is not correctable.",
  PROVENANCE_UNCHANGED:
    "The requested provenance matches the stored value; nothing to correct.",
};

/**
 * Decide what a staff correction should do.
 *
 * Note what is NOT checked here: the actor's role, and whether a reason was
 * supplied. Both are the shell's job — role because it needs a database read
 * against the User table (never a client claim), and the reason because it is a
 * request-validation concern. Keeping them out keeps this function total and
 * property-testable.
 */
export function planCorrection(
  subject: CorrectionSubject,
  requested: SyntheticSourceType,
): CorrectionPlan {
  if (subject.basis === "PLATFORM_GENERATED") {
    return {
      kind: "refuse",
      code: "PROVENANCE_PLATFORM_ATTESTED",
      message: REFUSALS.PROVENANCE_PLATFORM_ATTESTED,
    };
  }

  if (requested === subject.sourceType) {
    return {
      kind: "refuse",
      code: "PROVENANCE_UNCHANGED",
      message: REFUSALS.PROVENANCE_UNCHANGED,
    };
  }

  return {
    kind: "apply",
    from: subject.sourceType,
    to: requested,
    // A correction to UNKNOWN erases the claim entirely, so the basis goes with
    // it: "we believe nothing, on the authority of nothing" is the only coherent
    // encoding, and leaving a stale basis behind would make UNKNOWN look sourced.
    basis: requested === "UNKNOWN" ? null : (subject.basis ?? "AUTHOR_DECLARED"),
    reducesDisclosure:
      disclosureStrength(requested) < disclosureStrength(subject.sourceType),
  };
}
