/**
 * Canonical tenant-scoped CAS key builder.
 *
 * Provides the ONE canonical key scheme (D18) for content-addressed storage,
 * replacing multiple conflicting schemes. All storage paths MUST go through
 * these builders — never hand-roll a key string elsewhere.
 *
 * Keys are pure functions: no I/O, no clock, no external dependencies.
 */

// ---------------------------------------------------------------------------
// Preset union (closed enumeration — never user-supplied)
// ---------------------------------------------------------------------------

/**
 * Allowed derivative presets for a CAS object.
 * Only values in this union are accepted by casKey(); all other strings are rejected.
 */
export type CasPreset = "thumbnail" | "optimized";

const CAS_PRESETS: ReadonlySet<string> = new Set<CasPreset>([
  "thumbnail",
  "optimized",
]);

// ---------------------------------------------------------------------------
// Validation regexes (anchored allowlists — NOT blocklists)
// ---------------------------------------------------------------------------

/**
 * SHA-256 hex digest: exactly 64 lowercase hex characters.
 * Anchored so that path-traversal payloads, encoded dots, or extra characters
 * never pass validation.
 */
const SHA256_RE = /^[0-9a-f]{64}$/;

/**
 * CUID v1 format as generated by Prisma's @default(cuid()).
 * Format: 'c' followed by 24 lowercase alphanumeric characters (base-36 alphabet).
 * Total length: 25 characters.
 * See prisma/schema.prisma (id @default(cuid()) fields).
 *
 * Anchored to prevent traversal/injection: only [a-z0-9] within a fixed length band.
 */
const TENANT_ID_RE = /^c[a-z0-9]{24}$/;

/**
 * Upload session / pending key ID: we accept the same CUID format.
 * Prisma UploadSession.id is also @default(cuid()).
 */
const UPLOAD_ID_RE = /^c[a-z0-9]{24}$/;

// ---------------------------------------------------------------------------
// Typed error
// ---------------------------------------------------------------------------

export type CasKeyError =
  | { kind: "invalid_hash"; raw: string }
  | { kind: "invalid_tenant_id"; raw: string }
  | { kind: "invalid_upload_id"; raw: string }
  | { kind: "invalid_preset"; raw: string };

// ---------------------------------------------------------------------------
// validateContentHash
// ---------------------------------------------------------------------------

/**
 * Validate and lowercase-normalize an inbound content hash.
 *
 * Used at BOTH the upload boundary AND the serve entry point before any key
 * construction or DB lookup. Lowercase normalization prevents a split CAS
 * keyspace (two keys for the same bytes) caused by mixed-case hex.
 *
 * @returns The lowercase-normalized 64-char hex string, or a typed error.
 */
export function validateContentHash(
  raw: string,
): string | CasKeyError {
  const normalized = raw.toLowerCase();
  if (!SHA256_RE.test(normalized)) {
    return { kind: "invalid_hash", raw };
  }
  return normalized;
}

// ---------------------------------------------------------------------------
// casKey
// ---------------------------------------------------------------------------

/**
 * Build the canonical CAS storage key for a tenant-scoped object.
 *
 * Overload without preset: `cas/{tenantId}/{sha256}`
 * Overload with preset:    `cas/{tenantId}/{sha256}/{preset}`
 *
 * All inputs are validated against anchored allowlist regexes. The hash is
 * always lowercase-normalized so that the CAS keyspace is consistent.
 *
 * @returns The key string, or a typed error describing which input was invalid.
 */
export function casKey(
  tenantId: string,
  sha256: string,
): string | CasKeyError;
export function casKey(
  tenantId: string,
  sha256: string,
  preset: CasPreset,
): string | CasKeyError;
export function casKey(
  tenantId: string,
  sha256: string,
  preset?: CasPreset,
): string | CasKeyError {
  if (!TENANT_ID_RE.test(tenantId)) {
    return { kind: "invalid_tenant_id", raw: tenantId };
  }

  const normalized = sha256.toLowerCase();
  if (!SHA256_RE.test(normalized)) {
    return { kind: "invalid_hash", raw: sha256 };
  }

  if (preset !== undefined) {
    if (!CAS_PRESETS.has(preset)) {
      return { kind: "invalid_preset", raw: preset };
    }
    return `cas/${tenantId}/${normalized}/${preset}`;
  }

  return `cas/${tenantId}/${normalized}`;
}

// ---------------------------------------------------------------------------
// pendingKey
// ---------------------------------------------------------------------------

/**
 * Build the pending-upload staging key for a tenant-scoped upload.
 *
 * `pending/{tenantId}/{uploadId}`
 *
 * @returns The key string, or a typed error describing which input was invalid.
 */
export function pendingKey(
  tenantId: string,
  uploadId: string,
): string | CasKeyError {
  if (!TENANT_ID_RE.test(tenantId)) {
    return { kind: "invalid_tenant_id", raw: tenantId };
  }

  if (!UPLOAD_ID_RE.test(uploadId)) {
    return { kind: "invalid_upload_id", raw: uploadId };
  }

  return `pending/${tenantId}/${uploadId}`;
}

// ---------------------------------------------------------------------------
// processingKey
// ---------------------------------------------------------------------------

/**
 * Build the synchronous-image staging key for a tenant-scoped, content-hashed
 * object.
 *
 * `processing/{tenantId}/{sha256}`
 *
 * The sync-image upload path computes the content hash of the cleaned bytes
 * BEFORE moderation, so the staging key is content-addressed (unlike the
 * async `pendingKey`, which is keyed by uploadId before the hash is known). The
 * cleaned bytes live here until a verdict promotes them to `cas/`; `cas/` only
 * ever holds APPROVED bytes.
 *
 * @returns The key string, or a typed error describing which input was invalid.
 */
export function processingKey(
  tenantId: string,
  sha256: string,
): string | CasKeyError {
  if (!TENANT_ID_RE.test(tenantId)) {
    return { kind: "invalid_tenant_id", raw: tenantId };
  }

  const normalized = sha256.toLowerCase();
  if (!SHA256_RE.test(normalized)) {
    return { kind: "invalid_hash", raw: sha256 };
  }

  return `processing/${tenantId}/${normalized}`;
}

// ---------------------------------------------------------------------------
// Type guard helpers
// ---------------------------------------------------------------------------

/** Returns true when the result is a CasKeyError (not a key string). */
export function isCasKeyError(
  result: string | CasKeyError,
): result is CasKeyError {
  return typeof result === "object";
}

/** Returns the set of valid preset values (for exhaustiveness checks). */
export function allPresets(): readonly CasPreset[] {
  return ["thumbnail", "optimized"] as const;
}
