/**
 * Composed extension-model registry (O-1 design §12.3, Q8 item 4).
 *
 * The single generated source of truth for the extension-owned (`ext_*`) models
 * present in the composed schema. Three consumers agree on this contract:
 *
 * - **L1** feeds every entry's `model` into `TENANT_SCOPED_MODELS` so the
 *   scoped proxy enforces isolation and the `tenant-scope.test.ts` coverage
 *   tripwire stays green.
 * - **L2** (the fragment composer) GENERATES this array from the merged
 *   fragments — it is the "allowlist derived from the composed schema".
 * - **L4** iterates it for GDPR erasure: models with a non-null
 *   `erasureSubjectField` join the per-subject `deleteMany` sequence.
 *
 * **Empty today by design.** The only extension (`@skybber/ext-dogs`) owns no
 * Prisma tables yet — it is routes + taxonomy seeds. O-1 is infrastructure
 * ahead of its first table-owner (lane-02). L2 will emit entries here once a
 * fragment declares models.
 */

/**
 * One composed extension-owned model, as needed by isolation + erasure.
 */
export interface ExtensionModelRegistryEntry {
  /** Prisma model name (camelCase delegate key), e.g. "dogReminder". */
  readonly model: string;
  /** The mandatory tenant column injected on every scoped op, e.g. "tenantId". */
  readonly tenantField: string;
  /**
   * The column identifying the GDPR data subject for per-subject erasure, or
   * `null` when the model is `none-personal` / `cascade-only` (design §6).
   */
  readonly erasureSubjectField: string | null;
}

/**
 * The composed registry. Generated by the L2 composer; empty until a fragment
 * declares a model. Immutable at the type level.
 */
export const EXTENSION_MODEL_REGISTRY: readonly ExtensionModelRegistryEntry[] =
  [];
