/**
 * `trellis-schema compose` CLI entry — IMPERATIVE SHELL (PLAN L2, design §4.2).
 *
 * Thin wrapper: read the core schema + extension fragments from disk, run the
 * PURE {@link composeSchema}, and write the composed schema + generated registry
 * module. Optionally build + round-trip-verify the replay baseline
 * (`--baseline`) via the {@link buildReplayBaseline} shell.
 *
 * Coverage-excluded by design (it is I/O glue around the pure core + the
 * baseline shell, both tested elsewhere). Kept out of `PHASE0_NEW_FILES`.
 *
 * Usage:
 *   node extension-schema-composer-cli.js \
 *     --core <schema.prisma> \
 *     --fragment <extId>=<fragment.prisma> [--fragment ...] \
 *     --out <dir> \
 *     [--allow User,Entity,Tenant,Connection] \
 *     [--baseline --migrations <dir> --db <url> --direct <url>]
 */

import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import {
  composeSchema,
  type FragmentInput,
  type ComposedResult,
} from "./extension-schema-composer.js";
import type { ExtensionModelRegistryEntry } from "./extension-model-registry.js";
import {
  buildReplayBaseline,
  verifyRoundTrip,
} from "./extension-schema-baseline.js";

const DEFAULT_ALLOWLIST = ["User", "Entity", "Tenant"];

interface CliArgs {
  core: string;
  out: string;
  fragments: { extId: string; file: string }[];
  allow: string[];
  baseline: boolean;
  migrations?: string;
  db?: string;
  direct?: string;
}

export function parseArgs(argv: readonly string[]): CliArgs {
  const args: CliArgs = {
    core: "",
    out: "",
    fragments: [],
    allow: DEFAULT_ALLOWLIST,
    baseline: false,
  };
  for (let i = 0; i < argv.length; i += 1) {
    const a = argv[i];
    const next = (): string => {
      const v = argv[i + 1];
      if (v === undefined) throw new Error(`missing value for ${a}`);
      i += 1;
      return v;
    };
    switch (a) {
      case "--core":
        args.core = next();
        break;
      case "--out":
        args.out = next();
        break;
      case "--fragment": {
        const spec = next();
        const eq = spec.indexOf("=");
        if (eq === -1)
          throw new Error(`--fragment expects <extId>=<file>, got: ${spec}`);
        args.fragments.push({
          extId: spec.slice(0, eq),
          file: spec.slice(eq + 1),
        });
        break;
      }
      case "--allow":
        args.allow = next()
          .split(",")
          .map((s) => s.trim())
          .filter((s) => s.length > 0);
        break;
      case "--baseline":
        args.baseline = true;
        break;
      case "--migrations":
        args.migrations = next();
        break;
      case "--db":
        args.db = next();
        break;
      case "--direct":
        args.direct = next();
        break;
      default:
        throw new Error(`unknown argument: ${a}`);
    }
  }
  if (!args.core) throw new Error("--core <schema.prisma> is required");
  if (!args.out) throw new Error("--out <dir> is required");
  return args;
}

/** Render the generated registry module (mirrors the Phase 0 stub's shape). */
export function renderRegistryModule(
  registry: readonly ExtensionModelRegistryEntry[],
): string {
  const header = `// GENERATED by trellis-schema compose — DO NOT EDIT BY HAND.
// The composed extension-owned model registry (O-1 design §12.3, T0.5).
import type { ExtensionModelRegistryEntry } from "./extension-model-registry.js";

export const EXTENSION_MODEL_REGISTRY: readonly ExtensionModelRegistryEntry[] = `;
  const body = JSON.stringify(
    registry.map((e) => ({
      model: e.model,
      tenantField: e.tenantField,
      erasureSubjectField: e.erasureSubjectField,
    })),
    null,
    2,
  );
  return `${header}${body};\n`;
}

async function loadFragments(
  specs: readonly { extId: string; file: string }[],
): Promise<FragmentInput[]> {
  const out: FragmentInput[] = [];
  for (const spec of specs) {
    const source = await readFile(spec.file, "utf8");
    out.push({ extensionId: spec.extId, source });
  }
  return out;
}

export async function runCli(argv: readonly string[]): Promise<void> {
  const args = parseArgs(argv);
  const coreSchema = await readFile(args.core, "utf8");
  const fragments = await loadFragments(args.fragments);

  const result: ComposedResult = composeSchema({
    coreSchema,
    fragments,
    fkAllowlist: new Set(args.allow),
  });

  await mkdir(args.out, { recursive: true });
  const schemaOut = path.join(args.out, "schema.prisma");
  const registryOut = path.join(args.out, "extension-model-registry.generated.ts");
  await writeFile(schemaOut, result.schema, "utf8");
  await writeFile(registryOut, renderRegistryModule(result.registry), "utf8");
  process.stdout.write(
    `composed ${result.models.length} extension model(s) → ${schemaOut}\n`,
  );

  if (args.baseline) {
    if (!args.migrations || !args.db || !args.direct) {
      throw new Error(
        "--baseline requires --migrations, --db, and --direct (ephemeral local shadow DB)",
      );
    }
    const built = await buildReplayBaseline({
      apiDir: process.cwd(),
      migrationsDir: args.migrations,
      outDir: path.join(args.out, "baseline"),
      databaseUrl: args.db,
      directDatabaseUrl: args.direct,
    });
    const rt = await verifyRoundTrip(
      {
        apiDir: process.cwd(),
        migrationsDir: args.migrations,
        outDir: built.baselineDir,
        databaseUrl: args.db,
        directDatabaseUrl: args.direct,
      },
      built.baselineDir,
    );
    if (!rt.empty) {
      throw new Error(`baseline round-trip is NOT empty:\n${rt.output}`);
    }
    process.stdout.write(`baseline verified (round-trip empty) → ${built.baselinePath}\n`);
  }
}

// Node ESM entry guard.
if (import.meta.url === `file://${process.argv[1]}`) {
  runCli(process.argv.slice(2)).catch((err) => {
    process.stderr.write(`${err instanceof Error ? err.message : String(err)}\n`);
    process.exitCode = 1;
  });
}
